version: "3.2"
services:
  postgres:
    env_file:
      - postgres.env
    container_name: postgres
    build:
          context: .
          dockerfile: src/postgres/Dockerfile
    ports:
      - 5432:5432

volumes:
  node_modules:
