version: "3.2"
services:
  api:
    depends_on: [postgres, redis]
    build:
      context: ./src
      dockerfile: API.Dockerfile
    working_dir: /src
    ports:
      - 3000:3000
    env_file:
      - development.env

  postgres:
    env_file:
      - development.env
    container_name: postgres
    image: heimirthor/adventureworksforpostgres_db
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
        - 6379:6379