version: "3.2"
services:
  postgres:
    env_file:
      - postgres.env
    container_name: postgres
    image: heimirthor/adventureworksforpostgres_db
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
        - 6379:6379